FROM mariadb


RUN apt-get update \
 && apt-get install --no-install-recommends -y tzdata \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*

# Create app directory
# make the "en_US.UTF-8" locale so ~postgres~ mysql/mariadb will be utf-8 enabled by default

# RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* $ \
#  && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# ENV LANG en_US.utf8



COPY util/db.sql /docker-entrypoint-initdb.d/
COPY util/dummyData.sql /docker-entrypoint-initdb.d/

WORKDIR /usr/md
# COPY package*.json ./

# RUN npm install

# COPY . .

EXPOSE 3306
# ENTRYPOINT [ "mariadb.sh" ]

# CMD [ "npm", "run", "start:dev"]
